version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

dotenv: ['.env']

# env:

# vars:

includes:
  vagrant:
    taskfile: ./taskfiles/vagrant.yml
  tart:
    taskfile: ./taskfiles/tart.yml

tasks:
  default:
    desc: "Default task"
    cmds:
      - task --list
